# Exported functions ----

#' Summarize fuzz test results as a data frame
#'
#' @param x Object returned by \code{\link{fuzz_function}}.
#' @param ... Additional arguments to be passed to or from methods.
#' @param delim The delimiter to use for fields like \code{messages} or
#'    \code{warnings} in which there may be multiple results.
#'
#' @return A data frame with the following columns: \describe{
#'   \item{\code{fuzz_input}}{The name of the fuzz test performed.}
#'   \item{\code{output}}{Delimited outputs to the command line from the process, if applicable.}
#'   \item{\code{messages}}{Delimited messages, if applicable.}
#'   \item{\code{warnings}}{Delimited warnings, if applicable.}
#'   \item{\code{errors}}{Error returned, if applicable.}
#'   \item{\code{value_classes}}{Delimited classes of the object returned by the
#'    function, if applicable}
#'   \item{\code{results_index}}{Index of \code{x} from which the summary was
#'    produced.}
#'   }
#'
#' @importFrom purrr map2
#' @importFrom dplyr bind_rows
#' @export
as.data.frame.fuzz_results <- function(x, ..., delim = "; ") {

  # Map over the list 'x' and its indices simultaneously (Fix for row length mismatch)
  ldf <- purrr::map2(x, seq_along(x), function(result, i) {
    # 1. Parse the result into a data frame part
    df_part <- parse_fuzz_result_concat(result, delim = delim)

    # 2. Assign the results_index for all rows generated by this result
    # (The index 'i' is recycled to match the number of rows in df_part)
    df_part[["results_index"]] <- i

    df_part
  })

  # Combine the indexed data frames
  df <- dplyr::bind_rows(ldf)
  df
}

#' Access individual fuzz test results
#'
#' @param fr \code{fuzz_results} object
#' @param index The test index (by position) to access. Same as the
#'   \code{results_index} in the data frame returned by
#'   \code{\link{as.data.frame.fuzz_results}}.
#' @param ... Additional arguments must be named regex patterns that will be used to match against test names. The names of the patterns must match the function argument name(s) whose test names you wish to match.
#' @name fuzz_results
NULL

#' @describeIn fuzz_results Access the object returned by the fuzz test
#' @export
fuzz_value <- function(fr, index = NULL, ...) {
  res <- search_results(fr, index, ...)
  res[["test_result"]][["value"]]
}

#' @describeIn fuzz_results Access the call used for the fuzz test
#' @export
fuzz_call <- function(fr, index = NULL, ...) {
  res <- search_results(fr, index, ...)
  res[["test_result"]][["call"]]
}

# Internal functions ----

#' @importFrom purrr map map2_lgl detect walk
#' @importFrom assertthat assert_that is.count is.string
# Find elements of the search results list (Contains fix for map2_lgl and NULL returns)
search_results <- function(fr, index, ...) {
  assertthat::assert_that(inherits(fr, "fuzz_results"))

  # value supplied to index takes priority
  if (!is.null(index)) {
    assertthat::assert_that(assertthat::is.count(index) && index <= length(fr))
    res <- fr[[index]]
  } else {

    # Check for empty input list
    if (length(fr) == 0) {
      warning("Input 'fr' is empty.")
      return(list())
    }

    # if no index, then check based on test name
    .dots <- list(...)
    purrr::walk(.dots, function(p) assertthat::assert_that(assertthat::is.string(p)))

    # Ensure search names exist in the test results
    assertthat::assert_that(all(names(.dots) %in% names(fr[[1]][["test_name"]])))

    # purrr::detect returns NULL if nothing is found
    res <- purrr::detect(fr, function(el) {
      all(purrr::map2_lgl(.dots, names(.dots), function(p, n) {
        # FIX: Use any() to convert the vector of logical results from grepl()
        # into a single logical value required by purrr::map2_lgl().
        any(grepl(p, x = el[["test_name"]][[n]]))
      }))
    })

    # Correctly handle NULL return from purrr::detect
    if (is.null(res)) {
      warning("Zero matches found.")
      res <- list() # Return empty list, not NULL
    }
  }
  res
}


# For each result, create a one-row data frame of test names, outputs, messages,
# warnings, errors, and result classes.
parse_fuzz_result_concat <- function(fr, delim) {

  # Start building the data frame/tibble from test names (one row)
  dfr <- as.data.frame(fr[["test_name"]], stringsAsFactors = FALSE)

  elem_collapse <- function(elem) {
    # Check for NULL or zero length before collapsing
    if (is.null(elem) || length(elem) == 0) {
      NA_character_
    } else {
      paste(elem, collapse = delim)
    }
  }

  res_result <- fr[["test_result"]] # Cache the result list

  dfr[["output"]] <- elem_collapse(res_result[["output"]])
  dfr[["messages"]] <- elem_collapse(res_result[["messages"]])
  dfr[["warnings"]] <- elem_collapse(res_result[["warnings"]])
  dfr[["errors"]] <- elem_collapse(res_result[["errors"]])

  # Generate delimited classes string
  dfr[["value_classes"]] <- ifelse(
    is.null(res_result[["value"]]),
    NA_character_,
    paste(class(res_result[["value"]]), collapse = delim))

  dfr
}
